gb.api:
  endpoint:
    manufacturer-url: 'http://${gb.api.endpoint.base-uri}/api/v1/manufacturer'
  connection:
    period: 100
    max-period: 10000 #Mills
    max-attempt: 3
    connect-timeout: 10000 #Mills
#    connect-timeout-unit:
    read-timeout: 30000 #Mills
#    read-timeout-unit:
    follow-redirects: true
